name: Flutter CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2.16.0
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      working-directory: ./client
      
    - name: Verify Flutter installation
      run: flutter doctor -v
      working-directory: ./client
      
    - name: Run code generation
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      working-directory: ./client
      
    - name: Analyze code
      run: flutter analyze
      working-directory: ./client
      
    - name: Check formatting
      run: dart format --set-exit-if-changed .
      working-directory: ./client
      
    - name: Run tests
      run: flutter test
      working-directory: ./client
      
    - name: Generate test coverage
      run: flutter test --coverage
      working-directory: ./client